Fix: OCI registry when releasing helm chart (#105)
Inbstallation of helm chart use this path in the OCI registry: `oci://8gears.container-registry.com/library/n8n` but with latest release it is required to add an extra path `/n8n`

When trying:
```
helm pull oci://8gears.container-registry.com/library/n8n --version 0.24.0
Error: 8gears.container-registry.com/library/n8n:0.24.0: not found
```

it works when
```
helm pull oci://8gears.container-registry.com/library/n8n/n8n --version 0.24.0
```

But that's not the path used in the helm chart documentation.
CF: https://artifacthub.io/packages/helm/open-8gears/n8n/

You can also confirm that latest release `0.24.0` is not available in the helm chart.
CF: https://artifacthub.io/packages/helm/open-8gears/n8n/?modal=changelog